package chat.view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;
import javax.swing.SpringLayout;

import chat.controller.ChatController;

public class ChatPanel extends JPanel
{
	/**
	 * Initializes all objects for the panel
	 */
	private ChatController baseController;
	private SpringLayout baseLayout;
	private JButton submitButton;
	private JTextArea chatArea;
	private JTextField typingField;
	private JLabel promptLabel;
	private JLabel pictureLabel;
	private ImageIcon chatIcon;
	private JScrollPane textPane;
	private JButton tweetButton;
	private JButton analyzeButton;
	private JButton loadButton;
	private JButton saveButton;
	
	/**
	 * Returns the text field.
	 * @return
	 */
	public JTextField getTypingField()
	{
		return typingField;
	}

	/**
	 * Initilizes the objects for the panel.
	 * @param baseController
	 */
	public ChatPanel(ChatController baseController)
	{
		chatIcon = new ImageIcon (getClass().getResource("images/chatbot.png"));
		this.baseController = baseController;
		baseLayout = new SpringLayout();
		chatArea = new JTextArea(10,30);
		typingField = new JTextField(40);
		promptLabel = new JLabel("Hello, I'm Caliban");
		submitButton = new JButton("Submit");
		pictureLabel = new JLabel(chatIcon);
		tweetButton = new JButton("Tweet");
		analyzeButton = new JButton("Analyze Tweets");
		loadButton = new JButton("Load");
		saveButton = new JButton("Save");
		
		setupChatPane();
		setupPanel();
		setupLayout();
		setupListeners();
	}
	/**
	 * A dumping ground for code generated by the window editor.
	 */
	private void setupLayout()
	{
		baseLayout.putConstraint(SpringLayout.SOUTH, typingField, -60, SpringLayout.SOUTH, this);
		baseLayout.putConstraint(SpringLayout.NORTH, submitButton, 1, SpringLayout.NORTH, typingField);
		baseLayout.putConstraint(SpringLayout.EAST, submitButton, 0, SpringLayout.EAST, promptLabel);
		baseLayout.putConstraint(SpringLayout.EAST, chatArea, -43, SpringLayout.EAST, this);
		baseLayout.putConstraint(SpringLayout.WEST, typingField, 145, SpringLayout.WEST, this);
		baseLayout.putConstraint(SpringLayout.EAST, typingField, -43, SpringLayout.EAST, this);
		baseLayout.putConstraint(SpringLayout.NORTH, promptLabel, 161, SpringLayout.NORTH, this);
		baseLayout.putConstraint(SpringLayout.WEST, promptLabel, 10, SpringLayout.WEST, this);
		baseLayout.putConstraint(SpringLayout.WEST, chatArea, 24, SpringLayout.EAST, promptLabel);
		baseLayout.putConstraint(SpringLayout.SOUTH, pictureLabel, -6, SpringLayout.NORTH, promptLabel);
		baseLayout.putConstraint(SpringLayout.EAST, pictureLabel, 0, SpringLayout.EAST, promptLabel);
		baseLayout.putConstraint(SpringLayout.NORTH, chatArea, 10, SpringLayout.NORTH, this);
		baseLayout.putConstraint(SpringLayout.SOUTH, chatArea, -114, SpringLayout.SOUTH, this);
		baseLayout.putConstraint(SpringLayout.NORTH, textPane, 20, SpringLayout.NORTH, this);
		baseLayout.putConstraint(SpringLayout.WEST, textPane, 150, SpringLayout.WEST, this);
		baseLayout.putConstraint(SpringLayout.SOUTH, textPane, 275, SpringLayout.NORTH, this);
		baseLayout.putConstraint(SpringLayout.EAST, textPane, -20, SpringLayout.EAST, this);
		baseLayout.putConstraint(SpringLayout.NORTH, tweetButton, 0, SpringLayout.NORTH, analyzeButton);
		baseLayout.putConstraint(SpringLayout.WEST, tweetButton, 20, SpringLayout.EAST, analyzeButton);
		baseLayout.putConstraint(SpringLayout.WEST, analyzeButton, 0, SpringLayout.WEST, submitButton);
		baseLayout.putConstraint(SpringLayout.SOUTH, analyzeButton, -10, SpringLayout.SOUTH, this);
		baseLayout.putConstraint(SpringLayout.NORTH, loadButton, 0, SpringLayout.NORTH, analyzeButton);
		baseLayout.putConstraint(SpringLayout.EAST, loadButton, 0, SpringLayout.EAST, typingField);
		baseLayout.putConstraint(SpringLayout.NORTH, saveButton, 0, SpringLayout.NORTH, analyzeButton);
		baseLayout.putConstraint(SpringLayout.EAST, saveButton, -22, SpringLayout.WEST, loadButton);
	}
	
	private void setupChatPane()
	{
		chatArea.setLineWrap(true);
		chatArea.setWrapStyleWord(true);
		chatArea.setEditable(false);
		textPane = new JScrollPane(chatArea);
		textPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
		textPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
	}
	
	/**
	 * Adds the functionality to the button on the gui.
	 */
	private void setupListeners()
	{
		submitButton.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent click)
			{
				String userText = typingField.getText();
				chatArea.append("\nUser: " + userText);
				typingField.setText("");
				String response = baseController.userToChatbot(userText);
				chatArea.append("\nChatbot: " + response);
			}
		});
		
		tweetButton.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent click)
			{
				baseController.sendTweet("");
			}
		});
		
		analyzeButton.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent click)
			{
//				String user = typingField.getText();
//				String results = baseController.analyze(user);
				
				String results = baseController.locationSearch();
				chatArea.setText(results);
			}
		});
		
		loadButton.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent click)
			{
				
			}
		});
		
		saveButton.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent click)
			{
				
			}
		});
	}
	/**
	 * Adds the components to the panel.
	 */
	private void setupPanel()
	{
		this.setLayout(baseLayout);
		this.setBackground(Color.DARK_GRAY);
		this.add(textPane);
		this.add(typingField);
		this.add(submitButton);
		this.add(promptLabel);
		this.add(pictureLabel);
		this.add(tweetButton);
		this.add(analyzeButton);
		this.add(loadButton);
		this.add(saveButton);
		typingField.setToolTipText("Type here for the chatbot.");
		chatArea.setEnabled(false);
	}
}